name: RunsafeClans
main: no.runsafe.clans.RunsafeClans
version: 1.0.@BUILD@
author: Kruithne
description: Adds clan support!
commands:
  clan:
    description: Clan related commands.
  clanchat:
    description: Allows you to talk in clan chat.
    aliases: [c]
  clanspeak:
    description: Broadcast to a clan
    aliases: [cs]